# Generated by Django 5.2.15 on 2026-07-05 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('em_promocao', models.BooleanField(default=False)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('U', 'Unissex')], default='U', max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria')),
                ('colecao', models.ManyToManyField(blank=True, to='catalogo.colecao')),
                ('tamanho', models.ManyToManyField(blank=True, to='catalogo.tamanho')),
            ],
        ),
    ]
