# Generated by Django 6.0.7 on 2026-07-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_produto_imagem_produto_faixa_etaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
