# Generated by Django 6.0.7 on 2026-07-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_produto_cores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='genero',
        ),
        migrations.AddField(
            model_name='produto',
            name='publico',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('B', 'Bebês'), ('U', 'Unissex')], default='U', max_length=1),
        ),
    ]
