# Generated by Django 6.0.7 on 2026-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_produto_genero_produto_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='juros_parcelas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='parcelas',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_boleto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_pix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
