# Generated by Django 6.0.7 on 2026-07-30 17:20

from django.db import migrations

# criei para poder já inserir automaticamente no banco esses dados, porque com certeza
# quando colocar no Render, o banco vai estar vazio, assim, impossibilitando de fazer 
# o cadastro de produtos
def criar_dados_iniciais(apps, schema_editor):
    # cria tamanhos
    Tamanho = apps.get_model('catalogo', 'Tamanho')
    tamanhos = ["RN", "P", "M", "G", "GG", "1", "2", "3", "4", "6", "8", "10", "12", "14", "16"]
    for nome in tamanhos:
        Tamanho.objects.get_or_create(nome=nome)

    # cria categorias
    Categoria = apps.get_model('catalogo', 'Categoria')
    categorias = ["Vestidos", "Conjuntos", "Blusas", "Calças", "Shorts", "Macacões", "Outras peças"]
    for nome in categorias:
        Categoria.objects.get_or_create(nome=nome)

    # cria coleções (deixei aqui caso futuramente seja necessário)
    Colecao = apps.get_model('catalogo', 'Colecao')
    colecoes = ["Verão", "Inverno", "Primavera", "Outono", "Promoção"]
    for nome in colecoes:
        Colecao.objects.get_or_create(nome=nome)


def remover_dados_iniciais(apps, schema_editor):
    Tamanho = apps.get_model('catalogo', 'Tamanho')
    Tamanho.objects.all().delete()
    
    Categoria = apps.get_model('catalogo', 'Categoria')
    Categoria.objects.all().delete()
    
    Colecao = apps.get_model('catalogo', 'Colecao')
    Colecao.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('catalogo', '0001_initial'),  # depende da migração inicial
    ]

    operations = [
        migrations.RunPython(criar_dados_iniciais, remover_dados_iniciais),
    ]
