# Generated by Django 5.2.15 on 2026-07-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_produto_juros_parcelas_produto_parcelas_and_more'),
        ('catalogo', '0006_auto_20260730_1420'),
    ]

    operations = [
    ]
