# Generated by Django 5.2.15 on 2026-07-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_merge_20260731_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='publico',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('B', 'Bebês'), ('P', 'Primeiros passos')], default='U', max_length=1),
        ),
    ]
