# Generated by Django 6.0.7 on 2026-08-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='ativo',
        ),
    ]
